=== JiDarwish/databases2_opdrachten/week5/practricum/bestellingen/bestellingen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="bestellingen" type="bestellingenType" />
    <xs:complexType name="bestellingenType">
        <xs:sequence>
            <xs:element name="bestelling" type="bestellingType" minOccurs="0"  maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="bestellingType">
        <xs:sequence>
            <xs:element name="klant" type="xs:string"/>
            <xs:element name="product" type="productType" minOccurs="1" maxOccurs="unbounded" />
            <xs:element name="factuurbedrag" type="xs:decimal" />
        </xs:sequence>
        <xs:attribute name="bestelnummer" type="xs:integer" use="required" />
        <xs:attribute name="besteldatum" type="xs:date" use="required" />
    </xs:complexType>
    <xs:complexType name="productType">
        <xs:sequence>
            <xs:element name="code" type="xs:integer" />
            <xs:element name="aantal" type="xs:positiveInteger" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== JiDarwish/databases2_opdrachten/week5/practricum/bestellingen/bestellingen.xml
<?xml version="1.0" encoding="UTF-8"?>
<bestellingen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bestellingen.xsd">
    <bestelling bestelnummer="10001" besteldatum="2016-12-13">
        <klant>Willem van Buuren</klant>
        <product>
            <code>8712000019273</code>
            <aantal>4</aantal>
        </product>
        <factuurbedrag>21.80</factuurbedrag>
    </bestelling>
    <bestelling bestelnummer="10803" besteldatum="2017-01-05">
        <klant>Maxima van Buuren</klant>
        <product>
            <code>88718114778440</code>
            <aantal>1</aantal>
        </product>
        <product>
            <code>67157635</code>
            <aantal>1</aantal>
        </product>
        <product>
            <code>8714341063649</code>
            <aantal>1</aantal>
        </product>
        <factuurbedrag>11.90</factuurbedrag>
    </bestelling>
</bestellingen>
