=== JiDarwish/databases2_opdrachten/week5/practricum/artikelen/artikelen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="artikelen" type="ArtikelenType"/>
    <xs:complexType name="ArtikelenType">
        <xs:sequence>
            <xs:element name="artikel" type="ArtikelType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ArtikelType">
        <xs:sequence>
            <xs:element name="merk" type="xs:string"/>
            <xs:element name="omschrijving" type="xs:string"/>
            <xs:element name="prijs" type="PrijsValueType"/>
            <xs:element name="btw" type="BtwTariefType"/>
        </xs:sequence>
        <xs:attribute name="streepjescode" use="required" type="StreepjesCodeType"/>
    </xs:complexType>
    <xs:simpleType name="BtwTariefType">
        <xs:restriction base="xs:NCName">
            <xs:enumeration value="LAAG"/>
            <xs:enumeration value="HOOG"/>
            <xs:enumeration value="GEEN"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="PrijsValueType">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="StreepjesCodeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{13}"/>
            <xs:pattern value="[0-9]{8}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== JiDarwish/databases2_opdrachten/week5/practricum/artikelen/artikelen.xml
<?xml version="1.0" encoding="UTF-8"?>
<artikelen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Artikelen.xsd">
<!--<artikelen>-->
  <artikel streepjescode="8712100516429">
    <merk>Calve</merk>
    <omschrijving>Pindakaas 650g</omschrijving>
    <prijs>3.45</prijs>
    <btw>LAAG</btw>
  </artikel>
  <artikel streepjescode="8712000019273">
    <merk>Brand</merk>
    <omschrijving>Pilsener 6x33cl</omschrijving>
    <prijs>5.45</prijs>
    <btw>HOOG</btw>
  </artikel>
  <artikel streepjescode="67157635">
    <merk>Heinz</merk>
    <omschrijving>Tomatenketchup</omschrijving>
    <prijs>1.85</prijs>
    <btw>LAAG</btw>
  </artikel>
  <artikel streepjescode="8718114778440">
    <merk>Calve</merk>
    <omschrijving>Mayonaise licht romig</omschrijving>
    <prijs>2.25</prijs>
    <btw>LAAG</btw>
  </artikel>
  <artikel streepjescode="40414433">
    <merk>Lucky Strike</merk>
    <omschrijving>Original Red</omschrijving>
    <prijs>6.95</prijs>
    <btw>HOOG</btw>
  </artikel>
  <artikel streepjescode="8714341063649">
    <merk>PostNL</merk>
    <omschrijving>Postzegels 10st1</omschrijving>
    <prijs>7.80</prijs>
    <btw>GEEN</btw>
  </artikel>
</artikelen>
